/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;
import Model.Siswa;
import java.awt.event.KeyEvent;
import jdk.nashorn.internal.runtime.regexp.joni.exception.ErrorMessages;
/**
 *
 * @author MiRAI
 */
public class FormMasukkanDataSiswa extends javax.swing.JInternalFrame {
    Siswa sw = new Siswa();
    /**
     * Creates new form FormMasukkanDataSiswa
     */
    public FormMasukkanDataSiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisKelaminComboBox = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nisTxt = new javax.swing.JTextField();
        nisnTxt = new javax.swing.JTextField();
        namaTxt = new javax.swing.JTextField();
        tempatLahirTxt = new javax.swing.JTextField();
        simpaButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lakiButton = new javax.swing.JRadioButton();
        perempuanButton = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatTxt = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        tanggalLahirCalender = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Masukkan Data Siswa");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("NIS");

        jLabel2.setText("NISN");

        jLabel3.setText("Nama");

        jLabel4.setText("Tempat Lahir");

        jLabel5.setText("Jenis Kelamin");

        jLabel6.setText("Alamat");

        nisTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nisTxtKeyTyped(evt);
            }
        });

        nisnTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nisnTxtKeyTyped(evt);
            }
        });

        simpaButton.setText("Simpan");
        simpaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpaButtonActionPerformed(evt);
            }
        });

        jButton3.setText("Keluar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jenisKelaminComboBox.add(lakiButton);
        lakiButton.setText("Laki - Laki");

        jenisKelaminComboBox.add(perempuanButton);
        perempuanButton.setText("Perempuan");

        alamatTxt.setColumns(20);
        alamatTxt.setRows(5);
        jScrollPane1.setViewportView(alamatTxt);

        jLabel8.setText("Tanggal Lahir");

        tanggalLahirCalender.setDateFormatString("yyyy-MM-dd");

        jLabel7.setText("Upload Foto :");

        jButton1.setText("Browse");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(simpaButton)
                                .addGap(67, 67, 67)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lakiButton)
                                .addGap(18, 18, 18)
                                .addComponent(perempuanButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tanggalLahirCalender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                .addComponent(tempatLahirTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(namaTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nisnTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nisTxt, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nisnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tempatLahirTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(tanggalLahirCalender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lakiButton)
                    .addComponent(perempuanButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(simpaButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
  
    
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated

    }//GEN-LAST:event_formInternalFrameActivated

    private void simpaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpaButtonActionPerformed
       if(nisTxt.getText().equals("")|| nisnTxt.getText().equals("")|| namaTxt.getText().equals("")||
          tempatLahirTxt.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Tolong Jangan Dikosongkan!",
                    "Peringatan",JOptionPane.ERROR_MESSAGE);}
       else{
       String gender = null;
            if (lakiButton.isSelected()){
                gender = "L";
            }
            else if (perempuanButton.isSelected()){
                gender = "P";
            }
    
//        java.sql.Date tanggal = new java.sql.Date(tanggalLahirCalender.getDate().getTime());
//      String tanggal = null;  
        
           int pilihan = JOptionPane.showConfirmDialog(this, "Simpan data?", "Simpan data siswa", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);    
        if(pilihan == JOptionPane.YES_OPTION){
            sw.inputSiswa(nisTxt.getText(),
                    nisnTxt.getText(),
                    namaTxt.getText(),
                    tempatLahirTxt.getText(), 
                    tanggalLahirCalender.getDateFormatString(),
                    gender,
                    alamatTxt.getText());
        }
        JOptionPane.showMessageDialog(this, "Data berhasil disimpan!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
       }
    clear();    
    }//GEN-LAST:event_simpaButtonActionPerformed

    

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nisTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nisTxtKeyTyped
        filterNis(evt);
    }//GEN-LAST:event_nisTxtKeyTyped

    private void nisnTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nisnTxtKeyTyped
        filterNisn(evt);
    }//GEN-LAST:event_nisnTxtKeyTyped

      void filterNis(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
            JOptionPane.showMessageDialog(null,"Pada Kolom NIS Hanya Bisa Memasukan Karakter Angka", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }
      void filterNisn(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
            JOptionPane.showMessageDialog(null,"Pada Kolom NISN Hanya Bisa Memasukan Karakter Angka");
        }
    }
      
    final void clear(){
    nisTxt.setText("");
    nisnTxt.setText("");
    namaTxt.setText("");
    tempatLahirTxt.setText("");
    tanggalLahirCalender.setDate(null);
    jenisKelaminComboBox.clearSelection();
    alamatTxt.setText("");   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup jenisKelaminComboBox;
    private javax.swing.JRadioButton lakiButton;
    private javax.swing.JTextField namaTxt;
    private javax.swing.JTextField nisTxt;
    private javax.swing.JTextField nisnTxt;
    private javax.swing.JRadioButton perempuanButton;
    private javax.swing.JButton simpaButton;
    private com.toedter.calendar.JDateChooser tanggalLahirCalender;
    private javax.swing.JTextField tempatLahirTxt;
    // End of variables declaration//GEN-END:variables
}
