/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author MiRAI
 */
public class FormUtama extends javax.swing.JFrame {

    public static FormMasukkanDataSiswa formMasukkan = new FormMasukkanDataSiswa();
    public static FormDaftarSiswa formDaftar = new FormDaftarSiswa();
    
    public FormUtama() {
        initComponents();
        aturFrame(0.9 , true);
    }

    private void aturFrame(double skala, boolean tengah){
        Dimension dimensi = Toolkit.getDefaultToolkit().getScreenSize();
        setSize((int)(skala*dimensi.getWidth()), (int) (skala*dimensi.getHeight()));
        if (tengah){
            setLocation((int)(dimensi.getWidth()-dimensi.getWidth())/2, 
            (int)((dimensi.getHeight()-dimensi.getHeight())/2));
        }   
     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mdiDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        aplikasiMenu = new javax.swing.JMenu();
        deskripsiMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        selesaiMenuItem = new javax.swing.JMenuItem();
        masterDataMenu = new javax.swing.JMenu();
        masukkanMenuItem = new javax.swing.JMenuItem();
        ubahMenuItem = new javax.swing.JMenuItem();
        daftarMenuItem = new javax.swing.JMenuItem();
        printMenu = new javax.swing.JMenu();
        cetakMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Kartu Pelajar");

        javax.swing.GroupLayout mdiDesktopPaneLayout = new javax.swing.GroupLayout(mdiDesktopPane);
        mdiDesktopPane.setLayout(mdiDesktopPaneLayout);
        mdiDesktopPaneLayout.setHorizontalGroup(
            mdiDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        mdiDesktopPaneLayout.setVerticalGroup(
            mdiDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        aplikasiMenu.setText("Aplikasi");

        deskripsiMenuItem.setText("Deskripsi");
        aplikasiMenu.add(deskripsiMenuItem);
        aplikasiMenu.add(jSeparator1);

        selesaiMenuItem.setText("Selesai");
        aplikasiMenu.add(selesaiMenuItem);

        jMenuBar1.add(aplikasiMenu);

        masterDataMenu.setText("Master Data");

        masukkanMenuItem.setText("Masukkan Data Siswa");
        masukkanMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukkanMenuItemActionPerformed(evt);
            }
        });
        masterDataMenu.add(masukkanMenuItem);

        ubahMenuItem.setText("Ubah Data Siswa");
        masterDataMenu.add(ubahMenuItem);

        daftarMenuItem.setText("Daftar Siswa");
        daftarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarMenuItemActionPerformed(evt);
            }
        });
        masterDataMenu.add(daftarMenuItem);

        jMenuBar1.add(masterDataMenu);

        printMenu.setText("Print");

        cetakMenuItem.setText("Cetak Kartu");
        printMenu.add(cetakMenuItem);

        jMenuBar1.add(printMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mdiDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mdiDesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masukkanMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukkanMenuItemActionPerformed
    if (formMasukkan.isVisible()) { 
        try { formMasukkan.setSelected(true); } 
        catch (Exception ex) {} 
    } 
    else { 
        formMasukkan = new FormMasukkanDataSiswa(); 
        mdiDesktopPane.add(formMasukkan); 
        formMasukkan.setVisible(true); 
    }

    }//GEN-LAST:event_masukkanMenuItemActionPerformed

    private void daftarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarMenuItemActionPerformed
if (formDaftar.isVisible()) { 
        try { formDaftar.setSelected(true); } 
        catch (Exception ex) {} 
    } 
    else { 
        formDaftar   = new FormDaftarSiswa(); 
        mdiDesktopPane.add(formDaftar); 
        formDaftar.setVisible(true); 
    }
    }//GEN-LAST:event_daftarMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aplikasiMenu;
    private javax.swing.JMenuItem cetakMenuItem;
    private javax.swing.JMenuItem daftarMenuItem;
    private javax.swing.JMenuItem deskripsiMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu masterDataMenu;
    private javax.swing.JMenuItem masukkanMenuItem;
    private javax.swing.JDesktopPane mdiDesktopPane;
    private javax.swing.JMenu printMenu;
    private javax.swing.JMenuItem selesaiMenuItem;
    private javax.swing.JMenuItem ubahMenuItem;
    // End of variables declaration//GEN-END:variables
}
